version: "3.9"
services:
    api:
        build: montyhall-backend/
        ports:
            - "5080:80"
        depends_on: 
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment: 
            SA_PASSWORD: "myPass123"
            ACCEPT_EULA: "Y"
    ui:
        build: montyhall-frontend/
        ports: 
            - "3000:3000"
        depends_on: 
            - api